<a href="https://colab.research.google.com/github/arsingla786/MLFromScratch/blob/main/12Date%26Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Date**

In [2]:
import pandas as pd
import numpy as np

# For reproducibility
np.random.seed(42)

# Generate 200 rows
n = 200

data = {
    "date": pd.to_datetime(
        np.random.choice(
            pd.date_range("2018-01-01", "2019-12-31"),
            size=n
        )
    ),
    "product_id": np.random.randint(1000, 9999, size=n),
    "city_id": np.random.randint(1, 31, size=n),
    "orders": np.random.randint(1, 200, size=n)
}

df = pd.DataFrame(data)

# Sort by date (optional)
df = df.sort_values("date").reset_index(drop=True)

print(df.head())

        date  product_id  city_id  orders
0 2018-01-02        3255       30     141
1 2018-01-05        4327       26     101
2 2018-01-14        9155       17      36
3 2018-01-15        1569        4     161
4 2018-01-15        9050       24     118

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        200 non-null    datetime64[ns]
 1   product_id  200 non-null    int64
 2   city_id     200 non-null    int64
 3   orders      200 non-null    int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 6.4 KB

# **1. Extract year , month, day**

In [5]:
df['date_year'] = df['date'].dt.year
df.head()

        date  product_id  city_id  orders  date_year
0 2018-01-02        3255       30     141       2018
1 2018-01-05        4327       26     101       2018
2 2018-01-14        9155       17      36       2018
3 2018-01-15        1569        4     161       2018
4 2018-01-15        9050       24     118       2018

In [7]:
df['date_month'] = df['date'].dt.month
#use dt.month_name() for name of month
df.head()

        date  product_id  city_id  orders  date_year  date_month
0 2018-01-02        3255       30     141       2018           1
1 2018-01-05        4327       26     101       2018           1
2 2018-01-14        9155       17      36       2018           1
3 2018-01-15        1569        4     161       2018           1
4 2018-01-15        9050       24     118       2018           1

In [8]:
#day of week
df['date_dow'] = df['date'].dt.dayofweek
df.head()

        date  product_id  city_id  orders  date_year  date_month  date_dow
0 2018-01-02        3255       30     141       2018           1         1
1 2018-01-05        4327       26     101       2018           1         4
2 2018-01-14        9155       17      36       2018           1         6
3 2018-01-15        1569        4     161       2018           1         0
4 2018-01-15        9050       24     118       2018           1         0

In [9]:
#quarter
df['date_quarter'] = df['date'].dt.quarter
df.head()

,date,product_id,city_id,orders,date_year,date_month,date_dow,date_quarter
0,2018-01-02,3255,30,141,2018,1,1,1
1,2018-01-05,4327,26,101,2018,1,4,1
2,2018-01-14,9155,17,36,2018,1,6,1
3,2018-01-15,1569,4,161,2018,1,0,1
4,2018-01-15,9050,24,118,2018,1,0,1