<a href="https://colab.research.google.com/github/arsingla786/MLFromScratch/blob/main/8columnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Column Transformer** -> perform multiple preprocessing on different columns in same block

In [7]:
import seaborn as sns
df = sns.load_dataset('titanic')

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
transformer = ColumnTransformer(transformers= [
    ('t1',SimpleImputer(),['age']),
    ('t2',OneHotEncoder(drop='first'),['embarked','sex','embark_town','alive']),
    ('t3',OrdinalEncoder(categories = [['Third','Second','First']]),['class'])
],remainder='passthrough')

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest  =  train_test_split(df.drop('survived',axis=1),df['survived'],test_size=0.2,random_state=0)

In [21]:
xtrain_transformed = transformer.fit_transform(xtrain)
xtest_transformed = transformer.transform(xtest)

In [25]:
import pandas as pd
xtrain_transformed = pd.DataFrame(xtrain_transformed,columns=transformer.get_feature_names_out())

In [26]:
xtest_transformed = pd.DataFrame(xtest_transformed,columns=transformer.get_feature_names_out())

In [27]:
xtrain_transformed.head()

,t1__age,t2__embarked_Q,t2__embarked_S,t2__embarked_nan,t2__sex_male,t2__embark_town_Queenstown,t2__embark_town_Southampton,t2__embark_town_nan,t2__alive_yes,t3__class,remainder__pclass,remainder__sibsp,remainder__parch,remainder__fare,remainder__who,remainder__adult_male,remainder__deck,remainder__alone
0,29.745184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,0,2,15.2458,woman,False,NaN,False
1,31.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,2,0,0,10.5,man,True,NaN,True
2,31.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2,1,1,37.0042,man,True,NaN,False
3,20.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3,0,0,4.0125,man,True,NaN,True
4,21.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,3,0,0,7.25,man,True,NaN,True